---
- name: Prepare
  hosts: vms
  become: yes
  gather_facts: no
  vars_files:
    /Users/nmishin/conf/ansible/vault

  roles:
    - role: robertdebock.bootstrap
#    - role: robertdebock.core_dependencies
#    - role: robertdebock.cron
#    - role: robertdebock.buildtools
#    - role: robertdebock.python_pip
#    - role: robertdebock.selinux
#    - role: robertdebock.httpd
#    - role: robertdebock.redis
#    - role: robertdebock.remi
#      remi_enabled_repositories:
#        - php73
#      when:
#        - ansible_distribution != "Fedora"
#    - role: robertdebock.php
#    - role: robertdebock.php_fpm
#    - role: robertdebock.mysql
#      mysql_databases:
#        - name: owncloud
#          encoding: utf8
#          collation: utf8_bin
#      mysql_users:
#        - name: owncloud
#          password: 0wnCl0uD
#          priv: "owncloud.*:ALL"
    - role: robertdebock.owncloud

